// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AgentHistory struct {
	ID        string
	Prompt    string
	Response  string
	CreatedAt time.Time
}
