// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const createAgentHistory = `-- name: CreateAgentHistory :one
INSERT INTO agent_history (
    id, prompt, response, created_at
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, prompt, response, created_at
`

type CreateAgentHistoryParams struct {
	ID        string
	Prompt    string
	Response  string
	CreatedAt time.Time
}

func (q *Queries) CreateAgentHistory(ctx context.Context, arg CreateAgentHistoryParams) (AgentHistory, error) {
	row := q.db.QueryRowContext(ctx, createAgentHistory,
		arg.ID,
		arg.Prompt,
		arg.Response,
		arg.CreatedAt,
	)
	var i AgentHistory
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentHistory = `-- name: DeleteAgentHistory :exec
DELETE FROM agent_history
WHERE id = ?
`

func (q *Queries) DeleteAgentHistory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentHistory, id)
	return err
}

const getAgentHistory = `-- name: GetAgentHistory :one
SELECT id, prompt, response, created_at FROM agent_history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentHistory(ctx context.Context, id string) (AgentHistory, error) {
	row := q.db.QueryRowContext(ctx, getAgentHistory, id)
	var i AgentHistory
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentHistory = `-- name: ListAgentHistory :many
SELECT id, prompt, response, created_at FROM agent_history
ORDER BY created_at DESC
`

func (q *Queries) ListAgentHistory(ctx context.Context) ([]AgentHistory, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHistory
	for rows.Next() {
		var i AgentHistory
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.Response,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
